title: Azadeh Tofighi # your name (or website title) here
logo: "/images/portfolio1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <a href="https://www.linkedin.com/in/aztofighi/"><i class="fa-brands fa-linkedin"></i> LinkedIn Profile </a> <br>
  <a href="https://github.com/aztofighi"><i class="fa-brands fa-github"></i> GitHub Profile </a> <br>
  <a href="https://docs.google.com/document/d/1h0ODSjBtmwJlAEiUWkZh4b6u18Pi4_IS8xpFunYbZ7M/export?format=pdf">
  <i class="fa-solid fa-download"></i> Download Resume </a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
